### PR TITLE
Docker for ubuntu local development

### PR DESCRIPTION
**Pull request by MrMondrian**
## Related Issue(s)
  - https://github.com/mcgill-robotics/AUV-2024/issues/295

## Changes Made
- Add mesa drivers to dockerfile and main image to support visual rendering of ignition in docker. Only works in ubuntu. Add docker compose for easy launching of container that displays everything to the gui. Add optional gpu support for docker in the compose file that works

## Rationale/Other Solutions Considered
- Useful for if we get a PC in medn, we want to use our ubuntus for other things, and is a stepping stone towards being fully dockerized on all operating systems

## Tests Done
- Ran a simple mission fully dockerized with gui display
- Ran torch.cuda.is_available and it returned true

## Required Wiki Changes (if any)
- May need to add setup instructions for ubuntu

## Required install_dependencies.sh Changes (if any)
- For gpu support, need to install nvidia-container-toolkit

### CODE REVIEW

**Comment by frompotenza** [comment]
how smooth is the sim?

**Comment by MrMondrian** [comment]
> how smooth is the sim?

Perfectly smooth on ubuntu. Preliminary tests on windows show it will be slow. I have confidence it will be smooth on mac

**Review by antoinedang — CHANGES_REQUESTED** [review]
looks good, can you just make the necessary changes to install dependencies and the wiki? Then you can just bypass

**Comment by MrMondrian** [comment]
> looks good, can you just make the necessary changes to install dependencies and the wiki? Then you can just bypass

The dependency would be installed outside the container so it wouldn't need to be in the install dependencies script

**Comment by antoinedang** [comment]
> > looks good, can you just make the necessary changes to install dependencies and the wiki? Then you can just bypass
> 
> The dependency would be installed outside the container so it wouldn't need to be in the install dependencies script

Ok I guess just make the change to the wiki then, I forgot this would make it not necessary to run the install script lol

**Comment by MrMondrian** [comment]
> Ok I guess just make the change to the wiki then, I forgot this would make it not necessary to run the install script lol

[Done](https://github.com/mcgill-robotics/AUV-2024/wiki/6.1-Docker)

**Pull request merged**
