### PR TITLE
Additional model training script for Linux and not just colab

### PR DESCRIPTION
**Pull request by frompotenza**

### CODE REVIEW

**Comment by frompotenza** [comment]
I just made a few changes to the colab script so that I could run overnight. Colab has a resource limit of about an hour

**Comment by antoinedang** [comment]
accidental merge smh I meant to do the other PR for taking screenshots of sim cameras

**Comment by antoinedang** [comment]
but its fine its not breaking anything that wasnt already broken (I hope) so you can just merge anything that was left to noetic directly

**Comment by frompotenza** [comment]
> but its fine its not breaking anything that wasnt already broken (I hope) so you can just merge anything that was left to noetic directly

the changes are just for the pipeline tho. How would it break anything?

**Comment by antoinedang** [comment]
> > but its fine its not breaking anything that wasnt already broken (I hope) so you can just merge anything that was left to noetic directly
> 
> the changes are just for the pipeline tho. How would it break anything?

If we had a vision pipeline that was working it could've broken that, but my point was its fine cuz the vision pipeline was shabby anyway. So its fine to merge whatever to it since it cant break ROS stuff and the pipeline is already kinda broken

**Comment by frompotenza** [comment]
> If we had a vision pipeline that was working it could've broken that, but my point was its fine cuz the vision pipeline was shabby anyway. So its fine to merge whatever to it since it cant break ROS stuff and the pipeline is already kinda broken

Oh, I see. I don't think I changed anything in the colab pipeline. I think the changes showed in the commit are just part of the output cell (when you run the cell and it saves the output)

**Pull request merged**
