### PR TITLE
WIP add jetson docker updates

### PR DESCRIPTION
**Pull request by MrMondrian**
i dont have a stable internet connection right now so i cant build this image but if someone else could i would appreciate it

@antoinedang @frompotenza

### CODE REVIEW

**Comment by antoinedang** [comment]
i can build it tonight when i get home around 6pm but thats earliest I can do

also do you want to build it cross-platform or just a regular build?

**Comment by MrMondrian** [comment]
> i can build it tonight when i get home around 6pm but thats earliest I can do
> 
> also do you want to build it cross-platform or just a regular build?



> i can build it tonight when i get home around 6pm but thats earliest I can do
> 
> also do you want to build it cross-platform or just a regular build?

it doesn't need to be compile for multiple platforms but if you want to build with cross compilation from home or something that probably works

**Comment by antoinedang** [comment]
> > i can build it tonight when i get home around 6pm but thats earliest I can do
> > also do you want to build it cross-platform or just a regular build?
> 
> > i can build it tonight when i get home around 6pm but thats earliest I can do
> > also do you want to build it cross-platform or just a regular build?
> 
> it doesn't need to be compile for multiple platforms but if you want to build with cross compilation from home or something that probably works

ah i see now its on the jetson, for that I'd need to be at MEDN to see if it works. so might have to wait a bit

**Comment by antoinedang** [comment]
i can build poolside one but thats just a path change so i doubt thats what u need built

**Pull request closed without merging**
